# Generated by Django 4.1.3 on 2022-12-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'db_table': 'сountries',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'db_table': 'counties',
            },
        ),
        migrations.CreateModel(
            name='LevelOfPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Уровень цены',
                'verbose_name_plural': 'Уровни цены',
                'db_table': 'Levels_of_price',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Штат',
                'verbose_name_plural': 'Штаты',
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='TypeOfAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид достопримечательности',
                'verbose_name_plural': 'Виды достопримечательностей',
                'db_table': 'types_of_attraction',
            },
        ),
        migrations.CreateModel(
            name='TypeOfHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип отеля',
                'verbose_name_plural': 'Типы отелей',
                'db_table': 'types_of_hotels',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.country', verbose_name='Страна')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.region', verbose_name='Регион')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.state', verbose_name='Штат')),
                ('сounty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.county', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Деревня',
                'verbose_name_plural': 'Деревни',
                'db_table': 'villages',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.country', verbose_name='Страна')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.region', verbose_name='Регион')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.state', verbose_name='Штат')),
                ('сounty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.county', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'towns',
            },
        ),
        migrations.CreateModel(
            name='TouristAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('cid', models.CharField(max_length=30, unique=True, verbose_name='Идентификатор')),
                ('rating', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Рейтинг')),
                ('number_of_review', models.PositiveIntegerField(verbose_name='Число отзывов')),
                ('rating_5', models.PositiveIntegerField(null=True, verbose_name='Число отзывов c оценкой 5')),
                ('rating_4', models.PositiveIntegerField(null=True, verbose_name='Число отзывов c оценкой 4')),
                ('rating_3', models.PositiveIntegerField(null=True, verbose_name='Число отзывов c оценкой 3')),
                ('rating_2', models.PositiveIntegerField(null=True, verbose_name='Число отзывов c оценкой 2')),
                ('rating_1', models.PositiveIntegerField(null=True, verbose_name='Число отзывов c оценкой 1')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Долгота')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.city', verbose_name='Город')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.country', verbose_name='Страна')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.county', verbose_name='Район')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.region', verbose_name='Регион')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.state', verbose_name='Штат')),
                ('town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.town', verbose_name='Город')),
                ('type_of_attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_trip.typeofattraction')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.village', verbose_name='Деревня')),
            ],
            options={
                'verbose_name': 'Достопримечательность',
                'verbose_name_plural': 'Достопримечательности',
                'db_table': 'touristAttractions',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('cid', models.CharField(max_length=30, unique=True, verbose_name='Идентификатор')),
                ('rating', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Рейтинг')),
                ('number_of_review', models.PositiveIntegerField(verbose_name='Число отзывов')),
                ('rating_5', models.PositiveIntegerField(null=True, verbose_name='Число отзывов c оценкой 5')),
                ('rating_4', models.PositiveIntegerField(null=True, verbose_name='Число отзывов c оценкой 4')),
                ('rating_3', models.PositiveIntegerField(null=True, verbose_name='Число отзывов c оценкой 3')),
                ('rating_2', models.PositiveIntegerField(null=True, verbose_name='Число отзывов c оценкой 2')),
                ('rating_1', models.PositiveIntegerField(null=True, verbose_name='Число отзывов c оценкой 1')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Долгота')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.city', verbose_name='Город')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.country', verbose_name='Страна')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.county', verbose_name='Район')),
                ('level_of_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='google_trip.levelofprice')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.region', verbose_name='Регион')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.state', verbose_name='Штат')),
                ('town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.town', verbose_name='Город')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.village', verbose_name='Деревня')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
                'db_table': 'restuarants',
            },
        ),
        migrations.AddField(
            model_name='region',
            name='states',
            field=models.ManyToManyField(to='google_trip.state'),
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('cid', models.CharField(max_length=30, unique=True, verbose_name='Идентификатор')),
                ('rating', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Рейтинг')),
                ('number_of_review', models.PositiveIntegerField(verbose_name='Число отзывов')),
                ('rating_5', models.PositiveIntegerField(null=True, verbose_name='Число отзывов c оценкой 5')),
                ('rating_4', models.PositiveIntegerField(null=True, verbose_name='Число отзывов c оценкой 4')),
                ('rating_3', models.PositiveIntegerField(null=True, verbose_name='Число отзывов c оценкой 3')),
                ('rating_2', models.PositiveIntegerField(null=True, verbose_name='Число отзывов c оценкой 2')),
                ('rating_1', models.PositiveIntegerField(null=True, verbose_name='Число отзывов c оценкой 1')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Долгота')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.city', verbose_name='Город')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.country', verbose_name='Страна')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.county', verbose_name='Район')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.region', verbose_name='Регион')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.state', verbose_name='Штат')),
                ('town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.town', verbose_name='Город')),
                ('type_of_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_trip.typeofhotel')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.village', verbose_name='Деревня')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'db_table': 'hotels',
            },
        ),
        migrations.AddField(
            model_name='county',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.state', verbose_name='Штат'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.state', verbose_name='Штат'),
        ),
        migrations.AddField(
            model_name='city',
            name='сounty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_trip.county', verbose_name='Район'),
        ),
    ]
