# Generated by Django 4.1.3 on 2022-12-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='levelofprice',
            table='levels_of_price',
        ),
        migrations.AlterModelTable(
            name='touristattraction',
            table='tourist_attractions',
        ),
    ]
