# Generated by Django 4.1.3 on 2022-12-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_trip', '0002_alter_levelofprice_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
