# Generated by Django 4.1.3 on 2022-12-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_trip', '0003_alter_country_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='сounty',
            new_name='county',
        ),
    ]
