# Generated by Django 4.1.3 on 2022-12-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_trip', '0004_rename_сounty_city_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='town',
            old_name='сounty',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='сounty',
            new_name='county',
        ),
    ]
