# Generated by Django 4.1.3 on 2022-12-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_trip', '0005_rename_сounty_town_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelofprice',
            name='name',
        ),
        migrations.AddField(
            model_name='levelofprice',
            name='level',
            field=models.IntegerField(null=True, verbose_name='Уровень'),
        ),
    ]
