# Generated by Django 4.1.3 on 2022-12-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_trip', '0006_remove_levelofprice_name_levelofprice_level'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurants',
        ),
    ]
