# Generated by Django 4.1.3 on 2022-12-06 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google_trip', '0007_alter_restaurant_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='level_of_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='google_trip.levelofprice'),
        ),
    ]
