# Generated by Django 4.1.3 on 2022-12-06 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google_trip', '0008_alter_restaurant_level_of_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип ресторана',
                'verbose_name_plural': 'Типы ресторанов',
                'db_table': 'types_of_restaurant',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='type_of_restaurant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='google_trip.typeofrestaurant'),
            preserve_default=False,
        ),
    ]
