# Generated by Django 4.1.3 on 2022-12-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google_trip', '0009_typeofrestaurant_restaurant_type_of_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceOfHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_trip.hotels')),
            ],
            options={
                'verbose_name': 'Цена на отель',
                'verbose_name_plural': 'Цены на отели',
                'db_table': 'prices_of_hotel',
            },
        ),
    ]
