# Generated by Django 4.1.3 on 2022-12-07 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google_trip', '0010_priceofhotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='type_of_hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='google_trip.typeofhotel'),
        ),
    ]
