# Generated by Django 4.1.3 on 2022-12-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_trip', '0012_country_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristattraction',
            name='photo',
            field=models.ImageField(null=True, upload_to='tourist_attractions_images', verbose_name='Изображение'),
        ),
    ]
