# Generated by Django 4.1.3 on 2022-12-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_trip', '0013_touristattraction_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='photo',
            field=models.ImageField(null=True, upload_to='hotels_images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(null=True, upload_to='restaurants_images', verbose_name='Изображение'),
        ),
    ]
