# Generated by Django 4.1.3 on 2022-12-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_trip', '0014_hotels_photo_restaurant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='touristattraction',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
